//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel, IActionModalControls, IGlobalControls, ISEocontrol, IVisibilityControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Fact List
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("factList")]
		public IEnumerable<FactsList> FactList => this.Value<IEnumerable<FactsList>>("factList");

		///<summary>
		/// Facts Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("factsBackgroundImage")]
		public Umbraco.Core.Models.MediaWithCrops FactsBackgroundImage => this.Value<Umbraco.Core.Models.MediaWithCrops>("factsBackgroundImage");

		///<summary>
		/// Feature List Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("featureListLeft")]
		public IEnumerable<FeaturesList> FeatureListLeft => this.Value<IEnumerable<FeaturesList>>("featureListLeft");

		///<summary>
		/// Feature List Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("featureListRight")]
		public IEnumerable<FeaturesList> FeatureListRight => this.Value<IEnumerable<FeaturesList>>("featureListRight");

		///<summary>
		/// Features Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("featuresImage")]
		public Umbraco.Core.Models.MediaWithCrops FeaturesImage => this.Value<Umbraco.Core.Models.MediaWithCrops>("featuresImage");

		///<summary>
		/// Features Intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("featuresIntro")]
		public IHtmlString FeaturesIntro => this.Value<IHtmlString>("featuresIntro");

		///<summary>
		/// Homepage Banner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("homepageBanner")]
		public IEnumerable<BannerList> HomepageBanner => this.Value<IEnumerable<BannerList>>("homepageBanner");

		///<summary>
		/// Latest Informations
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("latestInformations")]
		public IHtmlString LatestInformations => this.Value<IHtmlString>("latestInformations");

		///<summary>
		/// Schedules
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("schedules")]
		public IEnumerable<SchedulePackage> Schedules => this.Value<IEnumerable<SchedulePackage>>("schedules");

		///<summary>
		/// Testimonial
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("testimonial")]
		public IEnumerable<TestimonialList> Testimonial => this.Value<IEnumerable<TestimonialList>>("testimonial");

		///<summary>
		/// Testimonials Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("testimonialsImage")]
		public Umbraco.Core.Models.MediaWithCrops TestimonialsImage => this.Value<Umbraco.Core.Models.MediaWithCrops>("testimonialsImage");

		///<summary>
		/// Testimonials Intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("testimonialsIntro")]
		public IHtmlString TestimonialsIntro => this.Value<IHtmlString>("testimonialsIntro");

		///<summary>
		/// Working Hours
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("workingHours")]
		public IEnumerable<WorkingPackage> WorkingHours => this.Value<IEnumerable<WorkingPackage>>("workingHours");

		///<summary>
		/// Working Hours Intro
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("workingHoursIntro")]
		public IHtmlString WorkingHoursIntro => this.Value<IHtmlString>("workingHoursIntro");

		///<summary>
		/// Include Modal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("includeModal")]
		public bool IncludeModal => ActionModalControls.GetIncludeModal(this);

		///<summary>
		/// Modal Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("modalButton")]
		public Umbraco.Web.Models.Link ModalButton => ActionModalControls.GetModalButton(this);

		///<summary>
		/// Modal Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("modalContent")]
		public IHtmlString ModalContent => ActionModalControls.GetModalContent(this);

		///<summary>
		/// Modal Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("modalImage")]
		public Umbraco.Core.Models.MediaWithCrops ModalImage => ActionModalControls.GetModalImage(this);

		///<summary>
		/// Modal Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("modalTitle")]
		public string ModalTitle => ActionModalControls.GetModalTitle(this);

		///<summary>
		/// Show Just Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("showJustImage")]
		public bool ShowJustImage => ActionModalControls.GetShowJustImage(this);

		///<summary>
		/// Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("address")]
		public string Address => GlobalControls.GetAddress(this);

		///<summary>
		/// Background image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("backgroundImage")]
		public Umbraco.Core.Models.MediaWithCrops BackgroundImage => GlobalControls.GetBackgroundImage(this);

		///<summary>
		/// Copyright Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("copyrightText")]
		public string CopyrightText => GlobalControls.GetCopyrightText(this);

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("description")]
		public IHtmlString Description => GlobalControls.GetDescription(this);

		///<summary>
		/// Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("email")]
		public string Email => GlobalControls.GetEmail(this);

		///<summary>
		/// Facebook Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("facebookLink")]
		public Umbraco.Web.Models.Link FacebookLink => GlobalControls.GetFacebookLink(this);

		///<summary>
		/// Instagram Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("instagramLink")]
		public Umbraco.Web.Models.Link InstagramLink => GlobalControls.GetInstagramLink(this);

		///<summary>
		/// Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("logo")]
		public Umbraco.Core.Models.MediaWithCrops Logo => GlobalControls.GetLogo(this);

		///<summary>
		/// Mobile Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mobilePhone")]
		public string MobilePhone => GlobalControls.GetMobilePhone(this);

		///<summary>
		/// Office Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("officePhone")]
		public string OfficePhone => GlobalControls.GetOfficePhone(this);

		///<summary>
		/// Twitter Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("twitterLink")]
		public Umbraco.Web.Models.Link TwitterLink => GlobalControls.GetTwitterLink(this);

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => SEocontrol.GetMetaDescription(this);

		///<summary>
		/// Meta Keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("metaKeywords")]
		public IEnumerable<string> MetaKeywords => SEocontrol.GetMetaKeywords(this);

		///<summary>
		/// Meta Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("metaName")]
		public string MetaName => SEocontrol.GetMetaName(this);

		///<summary>
		/// Hide From XML Sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("hideFromXMLSitemap")]
		public bool HideFromXmlsitemap => VisibilityControls.GetHideFromXmlsitemap(this);

		///<summary>
		/// Umbraco Navi Hide
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide => VisibilityControls.GetUmbracoNaviHide(this);
	}
}
